version: '3.9'

services:
  web:
    build: .
    container_name: vaultify_web
    command: gunicorn vaultify.wsgi.application:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=*
    
