# Generated by Django 5.1.4 on 2025-05-19 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_wallet_balance_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='onesignal_player_id',
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('gate', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_use', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
