# Generated by Django 5.1.4 on 2025-05-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_wallet_balance'),
        ('accounts', '0008_remove_userprofile_onesignal_player_id_accesscode'),
    ]

    operations = [
    ]
