# Generated by Django 5.1.4 on 2025-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_lostfounditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lostfound_images/'),
        ),
    ]
